#!/usr/bin/env bash
# killtree - Kill a process and all its descendants
#
# Usage:
#   killtree PID

has_pid() { [[ -n $1 ]]; }
has_pid "$1" || { echo "usage: killtree PID" >&2; exit 1; }

kill -9 $(pdsc "$1")
